-- liquibase formatted sql

-- changeset smirnovs:004-create-reviews-and-votes
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    film_id BIGINT NOT NULL REFERENCES films(id),
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    rating INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS review_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES reviews(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    vote_type SMALLINT NOT NULL CHECK (vote_type IN (1, -1)),
    UNIQUE (review_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_film ON reviews(film_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_review_votes_review ON review_votes(review_id);
CREATE INDEX IF NOT EXISTS idx_review_votes_user ON review_votes(user_id);